#pragma once

#if __cpp_exceptions == 199711L
#define ASYNC_CORO_COMPILE_WITH_EXCEPTIONS 1
#else
#define ASYNC_CORO_COMPILE_WITH_EXCEPTIONS 0
#endif

#ifndef ASYNC_CORO_WITH_EXCEPTIONS
#define ASYNC_CORO_WITH_EXCEPTIONS ASYNC_CORO_COMPILE_WITH_EXCEPTIONS
#endif

#ifndef ASYNC_CORO_ASSERT
#include <cassert>
#define ASYNC_CORO_ASSERT assert
#endif
